// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'animationItem': string;
  'buttonGroup': string;
  'editButton': string;
  'emptyMessage': string;
  'fileName': string;
  'header': string;
  'list': string;
  'listItemActionButton': string;
  'panel': string;
  'playButton': string;
}
export const cssExports: CssExports;
export default cssExports;
