// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backButton': string;
  'container': string;
  'content': string;
  'info': string;
  'placeholder': string;
}
export const cssExports: CssExports;
export default cssExports;
