// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeTab': string;
  'container': string;
  'tabBar': string;
  'tabContent': string;
}
export const cssExports: CssExports;
export default cssExports;
