// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'stateItem': string;
  'stateKey': string;
  'stateValue': string;
}
export const cssExports: CssExports;
export default cssExports;
