// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'assistant': string;
  'button': string;
  'chatContainer': string;
  'form': string;
  'input': string;
  'message': string;
  'messages': string;
  'system': string;
  'user': string;
}
export const cssExports: CssExports;
export default cssExports;
