// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'controlButton': string;
  'controls': string;
  'deleteButton': string;
  'editButton': string;
  'emptyMessage': string;
  'item': string;
  'itemList': string;
  'itemName': string;
  'primaryButton': string;
  'runButton': string;
  'secondaryButton': string;
  'section': string;
  'sectionTitle': string;
  'slider': string;
  'switch': string;
  'typeIndicator': string;
}
export const cssExports: CssExports;
export default cssExports;
