// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'container': string;
  'controlButton': string;
  'controls': string;
  'debugButton': string;
  'deleteButton': string;
  'editButton': string;
  'emptyMessage': string;
  'runButton': string;
  'section': string;
  'sectionTitle': string;
  'slider': string;
  'switch': string;
  'triggerItem': string;
  'triggerList': string;
  'triggerName': string;
}
export const cssExports: CssExports;
export default cssExports;
