// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menuButton': string;
  'menuContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
