// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hipHeightSlider': string;
  'hipSliderContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
