// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'controlRow': string;
  'emptyMessage': string;
}
export const cssExports: CssExports;
export default cssExports;
