// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'collapsed': string;
  'controlButton': string;
  'headerButtons': string;
  'panelContainer': string;
  'panelContent': string;
  'panelHeader': string;
  'panelTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
