// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'container': string;
  'menuButton': string;
  'sidebar': string;
}
export const cssExports: CssExports;
export default cssExports;
