// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionParams': string;
  'addButton': string;
  'content': string;
  'contextHint': string;
  'form': string;
  'formButtons': string;
  'paramControl': string;
  'paramError': string;
  'triggerItem': string;
}
export const cssExports: CssExports;
export default cssExports;
