// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'allow': string;
  'button': string;
  'buttons': string;
  'cancelButton': string;
  'confirmButton': string;
  'confirmMessage': string;
  'content': string;
  'details': string;
  'dialog': string;
  'disallow': string;
  'filePath': string;
  'info': string;
  'noThumbnail': string;
  'overlay': string;
  'separator': string;
  'subtitle': string;
  'thumbnail': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
