// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'header': string;
  'list': string;
  'listItem': string;
  'panel': string;
}
export const cssExports: CssExports;
export default cssExports;
