// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'slider': string;
  'sliderContainer': string;
  'sliderLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
