// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backButton': string;
  'container': string;
  'content': string;
  'editorLayout': string;
  'errorText': string;
  'footer': string;
  'keyframeEditorContainer': string;
  'mainEditorArea': string;
  'placeholder': string;
  'timelineContainer': string;
  'trackListContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
