// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'corner': string;
  'dopeSheetContainer': string;
  'keyframeGrid': string;
  'keyframeGridContainer': string;
  'keyframeMarker': string;
  'majorTick': string;
  'playhead': string;
  'ruler': string;
  'rulerContainer': string;
  'trackList': string;
  'trackListContainer': string;
  'trackName': string;
  'trackRow': string;
}
export const cssExports: CssExports;
export default cssExports;
