// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editorContainer': string;
  'error': string;
  'field': string;
  'placeholder': string;
  'title': string;
  'valueGrid': string;
  'valueLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
