// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controlButton': string;
  'controlsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
