// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'container': string;
  'keyframeMarker': string;
  'majorTick': string;
  'minorTick': string;
  'playhead': string;
  'tickLabel': string;
  'timelineSvg': string;
}
export const cssExports: CssExports;
export default cssExports;
