// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttonContainer': string;
  'buttonPrimary': string;
  'buttonRun': string;
  'buttonSecondary': string;
  'edgeAny': string;
  'edgeBoolean': string;
  'edgeDefault': string;
  'edgeEnum': string;
  'edgeExecution': string;
  'edgeNumber': string;
  'edgeString': string;
  'reactFlowWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
